
modLoader = "javafml"
loaderVersion = "[24,)"

[[mods]]
	modId = "pedestals"
	version = "1.0.1"
	displayName = "Pedestals"
	description = "WIP"

[[dependencies.pedestals]]
    modId = "forge"
    mandatory = true
    versionRange = "[24,)"
    ordering = "NONE"
    side = "BOTH"
    
[[dependencies.pedestals]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.13,]"
    ordering = "NONE"
    side = "BOTH"